name: employee ci cd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sudheern87/employee-image:latest .

      - name: Publish image to Docker Hub
        run: docker push sudheern87/employee-image:latest

  deploy:
    needs: build  # 👈 Ensures deploy runs after build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # 👈 Optional safety check

    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull sudheern87/employee-image:latest
            docker rm -f employee-container || true
            docker run -d -p 8080:8080 --name employee-container sudheern87/employee-image:latest
