name: employee ci cd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sudheern87/employee-image
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: [aws-ec2]  # Requires self-hosted runner on EC2 with label 'aws-ec2'

    steps:
      - name: Pull latest Docker image
        run: docker pull sudheern87/employee-image

      - name: Stop & remove old container (if running)
        run: |
          docker ps -q --filter "name=springboot-example-container" | grep -q . && \
          docker rm -f springboot-example-container || echo "No container to stop"

      - name: Run new container
        run: docker run -d -p 8080:8080 --name springboot-example-container sudheern87/employee-image
